# Generated by Django 4.0 on 2022-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_task_hint_task_hint_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
