# Generated by Django 4.1 on 2023-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_card_penalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
