# Generated by Django 4.0 on 2023-08-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_task_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
