# Generated by Django 4.1 on 2023-09-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('card', 'task')},
        ),
    ]
